<a href="https://colab.research.google.com/github/utjimmyx/python/blob/main/yfinance2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import yfinance as yf
import pandas as pd

In [ ]:
ticker = yf.Ticker("AAPL")

In [ ]:
ticker.info

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, and HomePod. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 164000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 63,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2023,
   'totalPay': 16239562,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Luca  Maestri',
   'age': 61,
   'title': 'CFO & Senior VP',
   'yearBorn': 1963,
   'fiscalYear': 2023,
   'totalPay': 4612242,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jeffrey E. Williams',
   'age': 60,
   'title': 'Chief Operating Officer',
   'yearBorn': 1964,
   'fiscalYear': 2023,
   'totalPay': 4637585,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 60,
   'title': 'Senior VP, General Counsel & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2023,
   'totalPay': 4618064,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 57,
   'title': 'Chief People Officer & Senior VP of Retail',
   'yearBorn': 1967,
   'fiscalYear': 2023,
   'totalPay': 4613369,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Chris  Kondo',
   'title': 'Senior Director of Corporate Accounting',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Adrian  Perica',
   'age': 50,
   'title': 'Head of Corporate Development',
   'yearBorn': 1974,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Michael  Fenger',
   'title': 'VP of Worldwide Sales',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 3,
 'boardRisk': 1,
 'compensationRisk': 3,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1735689600,
 'compensationAsOfEpochDate': 1703980800,
 'irWebsite': 'http://investor.apple.com/',
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 243.85,
 'open': 243.37,
 'dayLow': 241.89,
 'dayHigh': 244.18,
 'regularMarketPreviousClose': 243.85,
 'regularMarketOpen': 243.37,
 'regularMarketDayLow': 241.89,
 'regularMarketDayHigh': 244.18,
 'dividendRate': 1.0,
 'dividendYield': 0.0041,
 'exDividendDate': 1731024000,
 'payoutRatio': 0.1612,
 'fiveYearAvgDividendYield': 0.61,
 'beta': 1.24,
 'trailingPE': 40.026318,
 'forwardPE': 29.290522,
 'volume': 38477834,
 'regularMarketVolume': 38477834,
 'averageVolume': 44075057,
 'averageVolume10days': 52961650,
 'averageDailyVolume10Day': 52961650,
 'bid': 231.09,
 'ask': 255.61,
 'bidSize': 100,
 'askSize': 100,
 'marketCap': 3678581030912,
 'fiftyTwoWeekLow': 164.08,
 'fiftyTwoWeekHigh': 260.1,
 'priceToSalesTrailing12Months': 9.407293,
 'fiftyDayAverage': 237.7504,
 'twoHundredDayAverage': 213.7592,
 'trailingAnnualDividendRate': 0.98,
 'trailingAnnualDividendYield': 0.004018864,
 'currency': 'USD',
 'enterpriseValue': 3732474691584,
 'profitMargins': 0.23971,
 'floatShares': 15091184209,
 'sharesOutstanding': 15115799552,
 'sharesShort': 156458273,
 'sharesShortPriorMonth': 141037864,
 'sharesShortPreviousMonthDate': 1731628800,
 'dateShortInterest': 1734048000,
 'sharesPercentSharesOut': 0.0104,
 'heldPercentInsiders': 0.02056,
 'heldPercentInstitutions': 0.61924,
 'shortRatio': 3.67,
 'shortPercentOfFloat': 0.0104,
 'impliedSharesOutstanding': 15146300416,
 'bookValue': 3.767,
 'priceToBook': 64.603134,
 'lastFiscalYearEnd': 1727481600,
 'nextFiscalYearEnd': 1759017600,
 'mostRecentQuarter': 1727481600,
 'earningsQuarterlyGrowth': -0.358,
 'netIncomeToCommon': 93736001536,
 'trailingEps': 6.08,
 'forwardEps': 8.31,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 9.545,
 'enterpriseToEbitda': 27.718,
 '52WeekChange': 0.3141302,
 'SandP52WeekChange': 0.23197246,
 'lastDividendValue': 0.25,
 'lastDividendDate': 1731024000,
 'exchange': 'NMS',
 'quoteType': 'EQUITY',
 'symbol': 'AAPL',
 'underlyingSymbol': 'AAPL',
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'firstTradeDateEpochUtc': 345479400,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EST',
 'uuid': '8b10e4ae-9eeb-3684-921a-9ab27e4d87aa',
 'messageBoardId': 'finmb_24937',
 'gmtOffSetMilliseconds': -18000000,
 'currentPrice': 243.36,
 'targetHighPrice': 325.0,
 'targetLowPrice': 184.0,
 'targetMeanPrice': 247.32976,
 'targetMedianPrice': 250.0,
 'recommendationMean': 1.89362,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 42,
 'totalCash': 65171001344,
 'totalCashPerShare': 4.311,
 'ebitda': 134660997120,
 'totalDebt': 119058997248,
 'quickRatio': 0.745,
 'currentRatio': 0.867,
 'totalRevenue': 391034994688,
 'debtToEquity': 209.059,
 'revenuePerShare': 25.485,
 'returnOnAssets': 0.21464,
 'returnOnEquity': 1.5741299,
 'freeCashflow': 110846001152,
 'operatingCashflow': 118254002176,
 'earningsGrowth': -0.341,
 'revenueGrowth': 0.061,
 'grossMargins': 0.46206,
 'ebitdaMargins': 0.34437,
 'operatingMargins': 0.31171,
 'financialCurrency': 'USD',
 'trailingPegRatio': 2.2251}

In [ ]:
ticker.history()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-12-04 00:00:00-05:00,242.869995,244.110001,241.250000,243.009995,44383900,0.0,0.0
2024-12-05 00:00:00-05:00,243.990005,244.539993,242.130005,243.039993,40033900,0.0,0.0
2024-12-06 00:00:00-05:00,242.910004,244.630005,242.080002,242.839996,36870600,0.0,0.0
2024-12-09 00:00:00-05:00,241.830002,247.240005,241.750000,246.750000,44649200,0.0,0.0
2024-12-10 00:00:00-05:00,246.889999,248.210007,245.339996,247.770004,36914800,0.0,0.0
2024-12-11 00:00:00-05:00,247.960007,250.800003,246.259995,246.490005,45205800,0.0,0.0
2024-12-12 00:00:00-05:00,246.889999,248.740005,245.679993,247.960007,32777500,0.0,0.0
2024-12-13 00:00:00-05:00,247.820007,249.289993,246.240005,248.130005,33155300,0.0,0.0
2024-12-16 00:00:00-05:00,247.990005,251.380005,247.649994,251.039993,51694800,0.0,0.0
2024-12-17 00:00:00-05:00,250.080002,253.830002,249.779999,253.479996,51356400,0.0,0.0
2024-12-18 00:00:00-05:00,252.160004,254.279999,247.740005,248.050003,56774100,0.0,0.0
2024-12-19 00:00:00-05:00,247.500000,252.000000,247.089996,249.789993,60882300,0.0,0.0
2024-12-20 00:00:00-05:00,248.039993,255.000000,245.690002,254.490005,147495300,0.0,0.0
2024-12-23 00:00:00-05:00,254.770004,255.649994,253.449997,255.270004,40858800,0.0,0.0
2024-12-24 00:00:00-05:00,255.490005,258.209991,255.289993,258.200012,23234700,0.0,0.0
2024-12-26 00:00:00-05:00,258.190002,260.100006,257.630005,259.019989,27237100,0.0,0.0
2024-12-27 00:00:00-05:00,257.829987,258.700012,253.059998,255.589996,42355300,0.0,0.0
2024-12-30 00:00:00-05:00,252.229996,253.500000,250.750000,252.199997,35557500,0.0,0.0
2024-12-31 00:00:00-05:00,252.440002,253.279999,249.429993,250.419998,39480700,0.0,0.0
2025-01-02 00:00:00-05:00,248.929993,249.100006,241.820007,243.850006,55740700,0.0,0.0
2025-01-03 00:00:00-05:00,243.360001,244.179993,241.889999,243.360001,40202700,0.0,0.0

from matplotlib import pyplot as plt
_df_0['Open'].plot(kind='hist', bins=20, title='Open')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['High'].plot(kind='hist', bins=20, title='High')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Low'].plot(kind='hist', bins=20, title='Low')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['Close'].plot(kind='hist', bins=20, title='Close')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='Open', y='High', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='High', y='Low', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='Low', y='Close', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='Close', y='Volume', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Dividends']
  ys = series['Open']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_8.sort_values('Dividends', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Dividends')
_ = plt.ylabel('Open')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Dividends']
  ys = series['High']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('Dividends', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Dividends')
_ = plt.ylabel('High')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Dividends']
  ys = series['Low']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('Dividends', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Dividends')
_ = plt.ylabel('Low')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Dividends']
  ys = series['Close']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_11.sort_values('Dividends', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Dividends')
_ = plt.ylabel('Close')

from matplotlib import pyplot as plt
_df_12['Open'].plot(kind='line', figsize=(8, 4), title='Open')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_13['High'].plot(kind='line', figsize=(8, 4), title='High')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_14['Low'].plot(kind='line', figsize=(8, 4), title='Low')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_15['Close'].plot(kind='line', figsize=(8, 4), title='Close')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
ticker.history(period="max")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1980-12-12 00:00:00-05:00,0.098834,0.099264,0.098834,0.098834,469033600,0.0,0.0
1980-12-15 00:00:00-05:00,0.094108,0.094108,0.093678,0.093678,175884800,0.0,0.0
1980-12-16 00:00:00-05:00,0.087232,0.087232,0.086802,0.086802,105728000,0.0,0.0
1980-12-17 00:00:00-05:00,0.088951,0.089381,0.088951,0.088951,86441600,0.0,0.0
1980-12-18 00:00:00-05:00,0.091530,0.091959,0.091530,0.091530,73449600,0.0,0.0
...,...,...,...,...,...,...,...
2024-12-27 00:00:00-05:00,257.829987,258.700012,253.059998,255.589996,42355300,0.0,0.0
2024-12-30 00:00:00-05:00,252.229996,253.500000,250.750000,252.199997,35557500,0.0,0.0
2024-12-31 00:00:00-05:00,252.440002,253.279999,249.429993,250.419998,39480700,0.0,0.0
2025-01-02 00:00:00-05:00,248.929993,249.100006,241.820007,243.850006,55740700,0.0,0.0
2025-01-03 00:00:00-05:00,243.360001,244.179993,241.889999,243.360001,40202700,0.0,0.0

In [ ]:
balance_sheet = ticker.balance_sheet

In [ ]:
print(balance_sheet)

                                                      2024-09-30  \
Treasury Shares Number                                       NaN
Ordinary Shares Number                             15116786000.0
Share Issued                                       15116786000.0
Net Debt                                           76686000000.0
Total Debt                                        106629000000.0
...                                                          ...
Cash Cash Equivalents And Short Term Investments   65171000000.0
Other Short Term Investments                       35228000000.0
Cash And Cash Equivalents                          29943000000.0
Cash Equivalents                                    2744000000.0
Cash Financial                                     27199000000.0

                                                      2023-09-30  \
Treasury Shares Number                                       0.0
Ordinary Shares Number                             15550061000.0
Share Issued                                       15550061000.0
Net Debt                                           81123000000.0
Total Debt                                        111088000000.0
...                                                          ...
Cash Cash Equivalents And Short Term Investments   61555000000.0
Other Short Term Investments                       31590000000.0
Cash And Cash Equivalents                          29965000000.0
Cash Equivalents                                    1606000000.0
Cash Financial                                     28359000000.0

                                                      2022-09-30  \
Treasury Shares Number                                       NaN
Ordinary Shares Number                             15943425000.0
Share Issued                                       15943425000.0
Net Debt                                           96423000000.0
Total Debt                                        132480000000.0
...                                                          ...
Cash Cash Equivalents And Short Term Investments   48304000000.0
Other Short Term Investments                       24658000000.0
Cash And Cash Equivalents                          23646000000.0
Cash Equivalents                                    5100000000.0
Cash Financial                                     18546000000.0

                                                      2021-09-30 2020-09-30
Treasury Shares Number                                       NaN        NaN
Ordinary Shares Number                             16426786000.0        NaN
Share Issued                                       16426786000.0        NaN
Net Debt                                           89779000000.0        NaN
Total Debt                                        136522000000.0        NaN
...                                                          ...        ...
Cash Cash Equivalents And Short Term Investments   62639000000.0        NaN
Other Short Term Investments                       27699000000.0        NaN
Cash And Cash Equivalents                          34940000000.0        NaN
Cash Equivalents                                   17635000000.0        NaN
Cash Financial                                     17305000000.0        NaN

[68 rows x 5 columns]

In [ ]:
income_statement = ticker.income_stmt

In [ ]:
print(income_statement)

                                                        2024-09-30  \
Tax Effect Of Unusual Items                                    0.0
Tax Rate For Calcs                                        0.240912
Normalized EBITDA                                   134661000000.0
Net Income From Continuing Operation Net Minori...   93736000000.0
Reconciled Depreciation                              11445000000.0
Reconciled Cost Of Revenue                          210352000000.0
EBITDA                                              134661000000.0
EBIT                                                123216000000.0
Net Interest Income                                            NaN
Interest Expense                                               NaN
Interest Income                                                NaN
Normalized Income                                    93736000000.0
Net Income From Continuing And Discontinued Ope...   93736000000.0
Total Expenses                                      267819000000.0
Total Operating Income As Reported                  123216000000.0
Diluted Average Shares                                         NaN
Basic Average Shares                                           NaN
Diluted EPS                                                    NaN
Basic EPS                                                      NaN
Diluted NI Availto Com Stockholders                  93736000000.0
Net Income Common Stockholders                       93736000000.0
Net Income                                           93736000000.0
Net Income Including Noncontrolling Interests        93736000000.0
Net Income Continuous Operations                     93736000000.0
Tax Provision                                        29749000000.0
Pretax Income                                       123485000000.0
Other Income Expense                                   269000000.0
Other Non Operating Income Expenses                    269000000.0
Net Non Operating Interest Income Expense                      NaN
Interest Expense Non Operating                                 NaN
Interest Income Non Operating                                  NaN
Operating Income                                    123216000000.0
Operating Expense                                    57467000000.0
Research And Development                             31370000000.0
Selling General And Administration                   26097000000.0
Gross Profit                                        180683000000.0
Cost Of Revenue                                     210352000000.0
Total Revenue                                       391035000000.0
Operating Revenue                                   391035000000.0

                                                        2023-09-30  \
Tax Effect Of Unusual Items                                    0.0
Tax Rate For Calcs                                        0.147192
Normalized EBITDA                                   125820000000.0
Net Income From Continuing Operation Net Minori...   96995000000.0
Reconciled Depreciation                              11519000000.0
Reconciled Cost Of Revenue                          214137000000.0
EBITDA                                              125820000000.0
EBIT                                                114301000000.0
Net Interest Income                                   -183000000.0
Interest Expense                                      3933000000.0
Interest Income                                       3750000000.0
Normalized Income                                    96995000000.0
Net Income From Continuing And Discontinued Ope...   96995000000.0
Total Expenses                                      268984000000.0
Total Operating Income As Reported                  114301000000.0
Diluted Average Shares                               15812547000.0
Basic Average Shares                                 15744231000.0
Diluted EPS                                                   6.13
Basic EPS                                                     6.16
Diluted NI Availto Com Stockholders                  96995000000.0
Net Income Common Stockholders                       96995000000.0
Net Income                                           96995000000.0
Net Income Including Noncontrolling Interests        96995000000.0
Net Income Continuous Operations                     96995000000.0
Tax Provision                                        16741000000.0
Pretax Income                                       113736000000.0
Other Income Expense                                  -565000000.0
Other Non Operating Income Expenses                   -565000000.0
Net Non Operating Interest Income Expense             -183000000.0
Interest Expense Non Operating                        3933000000.0
Interest Income Non Operating                         3750000000.0
Operating Income                                    114301000000.0
Operating Expense                                    54847000000.0
Research And Development                             29915000000.0
Selling General And Administration                   24932000000.0
Gross Profit                                        169148000000.0
Cost Of Revenue                                     214137000000.0
Total Revenue                                       383285000000.0
Operating Revenue                                   383285000000.0

                                                        2022-09-30  \
Tax Effect Of Unusual Items                                    0.0
Tax Rate For Calcs                                           0.162
Normalized EBITDA                                   130541000000.0
Net Income From Continuing Operation Net Minori...   99803000000.0
Reconciled Depreciation                              11104000000.0
Reconciled Cost Of Revenue                          223546000000.0
EBITDA                                              130541000000.0
EBIT                                                119437000000.0
Net Interest Income                                   -106000000.0
Interest Expense                                      2931000000.0
Interest Income                                       2825000000.0
Normalized Income                                    99803000000.0
Net Income From Continuing And Discontinued Ope...   99803000000.0
Total Expenses                                      274891000000.0
Total Operating Income As Reported                  119437000000.0
Diluted Average Shares                               16325819000.0
Basic Average Shares                                 16215963000.0
Diluted EPS                                                   6.11
Basic EPS                                                     6.15
Diluted NI Availto Com Stockholders                  99803000000.0
Net Income Common Stockholders                       99803000000.0
Net Income                                           99803000000.0
Net Income Including Noncontrolling Interests        99803000000.0
Net Income Continuous Operations                     99803000000.0
Tax Provision                                        19300000000.0
Pretax Income                                       119103000000.0
Other Income Expense                                  -334000000.0
Other Non Operating Income Expenses                   -334000000.0
Net Non Operating Interest Income Expense             -106000000.0
Interest Expense Non Operating                        2931000000.0
Interest Income Non Operating                         2825000000.0
Operating Income                                    119437000000.0
Operating Expense                                    51345000000.0
Research And Development                             26251000000.0
Selling General And Administration                   25094000000.0
Gross Profit                                        170782000000.0
Cost Of Revenue                                     223546000000.0
Total Revenue                                       394328000000.0
Operating Revenue                                   394328000000.0

                                                        2021-09-30  \
Tax Effect Of Unusual Items                                    0.0
Tax Rate For Calcs                                           0.133
Normalized EBITDA                                   123136000000.0
Net Income From Continuing Operation Net Minori...   94680000000.0
Reconciled Depreciation                              11284000000.0
Reconciled Cost Of Revenue                          212981000000.0
EBITDA                                              123136000000.0
EBIT                                                111852000000.0
Net Interest Income                                    198000000.0
Interest Expense                                      2645000000.0
Interest Income                                       2843000000.0
Normalized Income                                    94680000000.0
Net Income From Continuing And Discontinued Ope...   94680000000.0
Total Expenses                                      256868000000.0
Total Operating Income As Reported                  108949000000.0
Diluted Average Shares                               16864919000.0
Basic Average Shares                                 16701272000.0
Diluted EPS                                                   5.61
Basic EPS                                                     5.67
Diluted NI Availto Com Stockholders                  94680000000.0
Net Income Common Stockholders                       94680000000.0
Net Income                                           94680000000.0
Net Income Including Noncontrolling Interests        94680000000.0
Net Income Continuous Operations                     94680000000.0
Tax Provision                                        14527000000.0
Pretax Income                                       109207000000.0
Other Income Expense                                    60000000.0
Other Non Operating Income Expenses                     60000000.0
Net Non Operating Interest Income Expense              198000000.0
Interest Expense Non Operating                        2645000000.0
Interest Income Non Operating                         2843000000.0
Operating Income                                    108949000000.0
Operating Expense                                    43887000000.0
Research And Development                             21914000000.0
Selling General And Administration                   21973000000.0
Gross Profit                                        152836000000.0
Cost Of Revenue                                     212981000000.0
Total Revenue                                       365817000000.0
Operating Revenue                                   365817000000.0

                                                       2020-09-30
Tax Effect Of Unusual Items                                   NaN
Tax Rate For Calcs                                            NaN
Normalized EBITDA                                             NaN
Net Income From Continuing Operation Net Minori...            NaN
Reconciled Depreciation                                       NaN
Reconciled Cost Of Revenue                                    NaN
EBITDA                                                        NaN
EBIT                                                          NaN
Net Interest Income                                   890000000.0
Interest Expense                                     2873000000.0
Interest Income                                      3763000000.0
Normalized Income                                             NaN
Net Income From Continuing And Discontinued Ope...            NaN
Total Expenses                                                NaN
Total Operating Income As Reported                            NaN
Diluted Average Shares                              17528214000.0
Basic Average Shares                                17352119000.0
Diluted EPS                                                  3.28
Basic EPS                                                    3.31
Diluted NI Availto Com Stockholders                           NaN
Net Income Common Stockholders                                NaN
Net Income                                                    NaN
Net Income Including Noncontrolling Interests                 NaN
Net Income Continuous Operations                              NaN
Tax Provision                                                 NaN
Pretax Income                                                 NaN
Other Income Expense                                          NaN
Other Non Operating Income Expenses                           NaN
Net Non Operating Interest Income Expense             890000000.0
Interest Expense Non Operating                       2873000000.0
Interest Income Non Operating                        3763000000.0
Operating Income                                              NaN
Operating Expense                                             NaN
Research And Development                                      NaN
Selling General And Administration                            NaN
Gross Profit                                                  NaN
Cost Of Revenue                                               NaN
Total Revenue                                                 NaN
Operating Revenue                                             NaN

In [ ]:
cash_flow = ticker.cashflow
print(cash_flow)

                                                    2024-09-30  \
Free Cash Flow                                  108807000000.0
Repurchase Of Capital Stock                     -94949000000.0
Repayment Of Debt                                -9958000000.0
Issuance Of Debt                                           0.0
Issuance Of Capital Stock                                  NaN
Capital Expenditure                              -9447000000.0
Interest Paid Supplemental Data                            NaN
Income Tax Paid Supplemental Data                26102000000.0
End Cash Position                                29943000000.0
Beginning Cash Position                          30737000000.0
Changes In Cash                                   -794000000.0
Financing Cash Flow                            -121983000000.0
Cash Flow From Continuing Financing Activities -121983000000.0
Net Other Financing Charges                      -5802000000.0
Cash Dividends Paid                             -15234000000.0
Common Stock Dividend Paid                      -15234000000.0
Net Common Stock Issuance                       -94949000000.0
Common Stock Payments                           -94949000000.0
Common Stock Issuance                                      NaN
Net Issuance Payments Of Debt                    -5998000000.0
Net Short Term Debt Issuance                      3960000000.0
Net Long Term Debt Issuance                      -9958000000.0
Long Term Debt Payments                          -9958000000.0
Long Term Debt Issuance                                    0.0
Investing Cash Flow                               2935000000.0
Cash Flow From Continuing Investing Activities    2935000000.0
Net Other Investing Changes                      -1308000000.0
Net Investment Purchase And Sale                 13690000000.0
Sale Of Investment                               62346000000.0
Purchase Of Investment                          -48656000000.0
Net Business Purchase And Sale                             NaN
Purchase Of Business                                       NaN
Net PPE Purchase And Sale                        -9447000000.0
Purchase Of PPE                                  -9447000000.0
Operating Cash Flow                             118254000000.0
Cash Flow From Continuing Operating Activities  118254000000.0
Change In Working Capital                         3651000000.0
Change In Other Working Capital                            NaN
Change In Other Current Liabilities              15552000000.0
Change In Other Current Assets                  -11731000000.0
Change In Payables And Accrued Expense            6020000000.0
Change In Payable                                 6020000000.0
Change In Account Payable                         6020000000.0
Change In Inventory                              -1046000000.0
Change In Receivables                            -5144000000.0
Changes In Account Receivables                   -3788000000.0
Other Non Cash Items                             -2266000000.0
Stock Based Compensation                         11688000000.0
Deferred Tax                                               NaN
Deferred Income Tax                                        NaN
Depreciation Amortization Depletion              11445000000.0
Depreciation And Amortization                    11445000000.0
Net Income From Continuing Operations            93736000000.0

                                                    2023-09-30  \
Free Cash Flow                                   99584000000.0
Repurchase Of Capital Stock                     -77550000000.0
Repayment Of Debt                               -11151000000.0
Issuance Of Debt                                  5228000000.0
Issuance Of Capital Stock                                  NaN
Capital Expenditure                             -10959000000.0
Interest Paid Supplemental Data                   3803000000.0
Income Tax Paid Supplemental Data                18679000000.0
End Cash Position                                30737000000.0
Beginning Cash Position                          24977000000.0
Changes In Cash                                   5760000000.0
Financing Cash Flow                            -108488000000.0
Cash Flow From Continuing Financing Activities -108488000000.0
Net Other Financing Charges                      -6012000000.0
Cash Dividends Paid                             -15025000000.0
Common Stock Dividend Paid                      -15025000000.0
Net Common Stock Issuance                       -77550000000.0
Common Stock Payments                           -77550000000.0
Common Stock Issuance                                      NaN
Net Issuance Payments Of Debt                    -9901000000.0
Net Short Term Debt Issuance                     -3978000000.0
Net Long Term Debt Issuance                      -5923000000.0
Long Term Debt Payments                         -11151000000.0
Long Term Debt Issuance                           5228000000.0
Investing Cash Flow                               3705000000.0
Cash Flow From Continuing Investing Activities    3705000000.0
Net Other Investing Changes                      -1337000000.0
Net Investment Purchase And Sale                 16001000000.0
Sale Of Investment                               45514000000.0
Purchase Of Investment                          -29513000000.0
Net Business Purchase And Sale                             NaN
Purchase Of Business                                       NaN
Net PPE Purchase And Sale                       -10959000000.0
Purchase Of PPE                                 -10959000000.0
Operating Cash Flow                             110543000000.0
Cash Flow From Continuing Operating Activities  110543000000.0
Change In Working Capital                        -6577000000.0
Change In Other Working Capital                            NaN
Change In Other Current Liabilities               3031000000.0
Change In Other Current Assets                   -5684000000.0
Change In Payables And Accrued Expense           -1889000000.0
Change In Payable                                -1889000000.0
Change In Account Payable                        -1889000000.0
Change In Inventory                              -1618000000.0
Change In Receivables                             -417000000.0
Changes In Account Receivables                   -1688000000.0
Other Non Cash Items                             -2227000000.0
Stock Based Compensation                         10833000000.0
Deferred Tax                                               NaN
Deferred Income Tax                                        NaN
Depreciation Amortization Depletion              11519000000.0
Depreciation And Amortization                    11519000000.0
Net Income From Continuing Operations            96995000000.0

                                                    2022-09-30  \
Free Cash Flow                                  111443000000.0
Repurchase Of Capital Stock                     -89402000000.0
Repayment Of Debt                                -9543000000.0
Issuance Of Debt                                  5465000000.0
Issuance Of Capital Stock                                  NaN
Capital Expenditure                             -10708000000.0
Interest Paid Supplemental Data                   2865000000.0
Income Tax Paid Supplemental Data                19573000000.0
End Cash Position                                24977000000.0
Beginning Cash Position                          35929000000.0
Changes In Cash                                 -10952000000.0
Financing Cash Flow                            -110749000000.0
Cash Flow From Continuing Financing Activities -110749000000.0
Net Other Financing Charges                      -6383000000.0
Cash Dividends Paid                             -14841000000.0
Common Stock Dividend Paid                      -14841000000.0
Net Common Stock Issuance                       -89402000000.0
Common Stock Payments                           -89402000000.0
Common Stock Issuance                                      NaN
Net Issuance Payments Of Debt                     -123000000.0
Net Short Term Debt Issuance                      3955000000.0
Net Long Term Debt Issuance                      -4078000000.0
Long Term Debt Payments                          -9543000000.0
Long Term Debt Issuance                           5465000000.0
Investing Cash Flow                             -22354000000.0
Cash Flow From Continuing Investing Activities  -22354000000.0
Net Other Investing Changes                      -2086000000.0
Net Investment Purchase And Sale                 -9560000000.0
Sale Of Investment                               67363000000.0
Purchase Of Investment                          -76923000000.0
Net Business Purchase And Sale                    -306000000.0
Purchase Of Business                              -306000000.0
Net PPE Purchase And Sale                       -10708000000.0
Purchase Of PPE                                 -10708000000.0
Operating Cash Flow                             122151000000.0
Cash Flow From Continuing Operating Activities  122151000000.0
Change In Working Capital                         1200000000.0
Change In Other Working Capital                    478000000.0
Change In Other Current Liabilities               6110000000.0
Change In Other Current Assets                   -6499000000.0
Change In Payables And Accrued Expense            9448000000.0
Change In Payable                                 9448000000.0
Change In Account Payable                         9448000000.0
Change In Inventory                               1484000000.0
Change In Receivables                            -9343000000.0
Changes In Account Receivables                   -1823000000.0
Other Non Cash Items                              1006000000.0
Stock Based Compensation                          9038000000.0
Deferred Tax                                       895000000.0
Deferred Income Tax                                895000000.0
Depreciation Amortization Depletion              11104000000.0
Depreciation And Amortization                    11104000000.0
Net Income From Continuing Operations            99803000000.0

                                                    2021-09-30    2020-09-30
Free Cash Flow                                   92953000000.0           NaN
Repurchase Of Capital Stock                     -85971000000.0           NaN
Repayment Of Debt                                -8750000000.0           NaN
Issuance Of Debt                                 20393000000.0           NaN
Issuance Of Capital Stock                         1105000000.0   880000000.0
Capital Expenditure                             -11085000000.0           NaN
Interest Paid Supplemental Data                   2687000000.0  3002000000.0
Income Tax Paid Supplemental Data                25385000000.0           NaN
End Cash Position                                35929000000.0           NaN
Beginning Cash Position                          39789000000.0           NaN
Changes In Cash                                  -3860000000.0           NaN
Financing Cash Flow                             -93353000000.0           NaN
Cash Flow From Continuing Financing Activities  -93353000000.0           NaN
Net Other Financing Charges                      -5580000000.0           NaN
Cash Dividends Paid                             -14467000000.0           NaN
Common Stock Dividend Paid                      -14467000000.0           NaN
Net Common Stock Issuance                       -85971000000.0           NaN
Common Stock Payments                           -85971000000.0           NaN
Common Stock Issuance                             1105000000.0   880000000.0
Net Issuance Payments Of Debt                    12665000000.0           NaN
Net Short Term Debt Issuance                      1022000000.0           NaN
Net Long Term Debt Issuance                      11643000000.0           NaN
Long Term Debt Payments                          -8750000000.0           NaN
Long Term Debt Issuance                          20393000000.0           NaN
Investing Cash Flow                             -14545000000.0           NaN
Cash Flow From Continuing Investing Activities  -14545000000.0           NaN
Net Other Investing Changes                       -385000000.0           NaN
Net Investment Purchase And Sale                 -3075000000.0           NaN
Sale Of Investment                              106483000000.0           NaN
Purchase Of Investment                         -109558000000.0           NaN
Net Business Purchase And Sale                     -33000000.0 -1524000000.0
Purchase Of Business                               -33000000.0 -1524000000.0
Net PPE Purchase And Sale                       -11085000000.0           NaN
Purchase Of PPE                                 -11085000000.0           NaN
Operating Cash Flow                             104038000000.0           NaN
Cash Flow From Continuing Operating Activities  104038000000.0           NaN
Change In Working Capital                        -4911000000.0           NaN
Change In Other Working Capital                   1676000000.0  2081000000.0
Change In Other Current Liabilities               7475000000.0           NaN
Change In Other Current Assets                   -8042000000.0           NaN
Change In Payables And Accrued Expense           12326000000.0           NaN
Change In Payable                                12326000000.0           NaN
Change In Account Payable                        12326000000.0           NaN
Change In Inventory                              -2642000000.0           NaN
Change In Receivables                           -14028000000.0           NaN
Changes In Account Receivables                  -10125000000.0           NaN
Other Non Cash Items                             -4921000000.0           NaN
Stock Based Compensation                          7906000000.0           NaN
Deferred Tax                                     -4774000000.0  -215000000.0
Deferred Income Tax                              -4774000000.0  -215000000.0
Depreciation Amortization Depletion              11284000000.0           NaN
Depreciation And Amortization                    11284000000.0           NaN
Net Income From Continuing Operations            94680000000.0           NaN

In [ ]:
with pd.ExcelWriter("AAPL.xlsx") as writer:
    balance_sheet.to_excel(writer, sheet_name="Balance Sheet")
    income_statement.to_excel(writer, sheet_name="Income Statement")
    cash_flow.to_excel(writer, sheet_name="Cash Flow")

In [ ]:
ticker.eps_trend

     current  7daysAgo  30daysAgo  60daysAgo  90daysAgo
0q   2.34897   2.35100    2.34977    2.35230    2.38261
+1q  1.67928   1.67860    1.68095    1.68125    1.70681
0y   7.38751   7.38756    7.38754    7.37191    7.40367
+1y  8.27612   8.27620    8.26639    8.24251    8.31647

from matplotlib import pyplot as plt
_df_16['current'].plot(kind='hist', bins=20, title='current')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_17['7daysAgo'].plot(kind='hist', bins=20, title='7daysAgo')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_18['30daysAgo'].plot(kind='hist', bins=20, title='30daysAgo')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_19['60daysAgo'].plot(kind='hist', bins=20, title='60daysAgo')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_20.plot(kind='scatter', x='current', y='7daysAgo', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_21.plot(kind='scatter', x='7daysAgo', y='30daysAgo', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_22.plot(kind='scatter', x='30daysAgo', y='60daysAgo', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_23.plot(kind='scatter', x='60daysAgo', y='90daysAgo', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_24['current'].plot(kind='line', figsize=(8, 4), title='current')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_25['7daysAgo'].plot(kind='line', figsize=(8, 4), title='7daysAgo')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_26['30daysAgo'].plot(kind='line', figsize=(8, 4), title='30daysAgo')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_27['60daysAgo'].plot(kind='line', figsize=(8, 4), title='60daysAgo')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
ticker.dividends

Date
1987-05-11 00:00:00-04:00    0.000536
1987-08-10 00:00:00-04:00    0.000536
1987-11-17 00:00:00-05:00    0.000714
1988-02-12 00:00:00-05:00    0.000714
1988-05-16 00:00:00-04:00    0.000714
                               ...
2023-11-10 00:00:00-05:00    0.240000
2024-02-09 00:00:00-05:00    0.240000
2024-05-10 00:00:00-04:00    0.250000
2024-08-12 00:00:00-04:00    0.250000
2024-11-08 00:00:00-05:00    0.250000
Name: Dividends, Length: 85, dtype: float64